//! Numerical parity (Rust forward pass vs. the upstream torch `DetectModel`)
//! and provider smoke tests for FireRedVAD.

use super::model::FireRedVadModel;
use super::provider::FireRedVadProvider;

/// Golden fixture: a 3 s (48,000-sample) excerpt of `fixtures/jfk.wav`
/// (leading silence then speech) plus the reference per-10ms-frame speech
/// probabilities from the official upstream torch `FireRedVad.detect(...,
/// do_postprocess=False)` pipeline (`fireredvad/vad.py`), generated by a
/// one-off export script against the vendored `VAD/model.pth.tar` +
/// `VAD/cmvn.ark` checkpoint. Binary layout: magic `"FRVG"`, `u32
/// n_samples`, `u32 n_frames`, `f32[n_samples]` samples, `f32[n_frames]`
/// reference probs (all little-endian).
fn golden() -> (Vec<f32>, Vec<f32>) {
    const GOLDEN: &[u8] = include_bytes!("../assets/firered_vad_16k_golden.bin");
    assert_eq!(&GOLDEN[0..4], b"FRVG", "golden magic");
    let n_samples = u32::from_le_bytes(GOLDEN[4..8].try_into().unwrap()) as usize;
    let n_frames = u32::from_le_bytes(GOLDEN[8..12].try_into().unwrap()) as usize;
    let mut off = 12;
    let mut read = |n: usize| -> Vec<f32> {
        let out = GOLDEN[off..off + n * 4]
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect();
        off += n * 4;
        out
    };
    let samples = read(n_samples);
    let probs = read(n_frames);
    (samples, probs)
}

/// Bisects the frame axis to report the first sizeable divergence, mirroring
/// the layered parity-debugging approach used for the other FireRed family
/// models (fbank frontend correct up to frame X, then divergence starts).
fn max_abs_diff_with_location(got: &[f32], want: &[f32]) -> (f32, usize) {
    assert_eq!(got.len(), want.len(), "frame count mismatch");
    let mut worst = 0.0f32;
    let mut worst_idx = 0;
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        let d = (g - w).abs();
        if d > worst {
            worst = d;
            worst_idx = i;
        }
    }
    (worst, worst_idx)
}

#[test]
fn forward_pass_matches_upstream_torch_reference_within_tolerance() {
    let (samples, reference_probs) = golden();
    let model = FireRedVadModel::embedded().expect("vendored firered VAD weights");
    let probs = model.probabilities(&samples);

    assert_eq!(
        probs.len(),
        reference_probs.len(),
        "frame count must match the upstream 10ms-frame cadence"
    );
    // Measured max abs prob error is ~1.5e-6 (f32 accumulation noise); 1e-3
    // leaves ample headroom while still catching a wrong FSMN offset/sign.
    let (max_diff, at) = max_abs_diff_with_location(&probs, &reference_probs);
    assert!(
        max_diff < 1e-3,
        "max abs prob error {max_diff} at frame {at} (got {}, want {}) exceeds tolerance",
        probs[at],
        reference_probs[at],
    );
}

#[test]
fn probabilities_are_finite_and_in_unit_range() {
    let (samples, _) = golden();
    let model = FireRedVadModel::embedded().expect("vendored firered VAD weights");
    let probs = model.probabilities(&samples);
    assert!(!probs.is_empty());
    assert!(
        probs
            .iter()
            .all(|p| p.is_finite() && (0.0..=1.0).contains(p))
    );
}

#[test]
fn empty_audio_returns_no_probabilities() {
    let model = FireRedVadModel::embedded().expect("vendored firered VAD weights");
    assert!(model.probabilities(&[]).is_empty());
}

#[test]
fn shared_model_loads() {
    assert!(super::shared_model().is_some());
}

#[test]
fn provider_shared_computes_speech_slices_on_golden_clip() {
    use crate::longform::{LongFormOptions, LongFormVadProvider};

    let (samples, _) = golden();
    let provider = FireRedVadProvider::shared().expect("shared firered VAD provider");
    let options = LongFormOptions::default();
    let slices = provider
        .compute_speech_slices(&samples, super::frontend::SAMPLE_RATE_HZ, &options)
        .expect("speech slices");
    // The golden clip is leading silence then speech; expect at least one
    // detected speech span, and all spans within bounds and non-empty.
    assert!(!slices.is_empty(), "expected at least one speech span");
    for slice in &slices {
        assert!(slice.end_sample > slice.start_sample);
        assert!(slice.end_sample <= samples.len());
    }
}

#[test]
fn provider_rejects_wrong_sample_rate() {
    use crate::longform::{LongFormOptions, LongFormVadProvider};

    let provider = FireRedVadProvider::shared().expect("shared firered VAD provider");
    let samples = vec![0.0f32; 8_000];
    let err = provider
        .compute_speech_slices(&samples, 8_000, &LongFormOptions::default())
        .expect_err("wrong sample rate must fail closed");
    assert!(err.contains("16000"));
}
