/* Generated by cbindgen from crates/openasr-ffi/src/lib.rs. Do not edit by
 * hand -- run scripts/generate-ffi-header.sh to regenerate. */

#ifndef OPENASR_H
#define OPENASR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned by every `openasr_*` call that can fail. `Ok` is
 * always `0`; every other variant means the requested handle/buffer was not
 * produced (or not mutated) and the caller should consult
 * [`openasr_last_error_message`].
 */
typedef enum OpenAsrStatus {
  /**
   * Call succeeded.
   */
  OPEN_ASR_STATUS_OK = 0,
  /**
   * A required pointer was null, or an argument was out of the range this
   * v1 API supports (e.g. a sample rate other than 16000, or a channel
   * count other than mono).
   */
  OPEN_ASR_STATUS_INVALID_ARGUMENT = 1,
  /**
   * The `.oasr` path was rejected: missing, not a recognized runtime
   * format, or failed the local-path/format trust checks.
   */
  OPEN_ASR_STATUS_MODEL_LOAD_FAILED = 2,
  /**
   * The engine returned an error while transcribing (bad/corrupt pack
   * contents, unsupported model family, decode failure, ...).
   */
  OPEN_ASR_STATUS_TRANSCRIBE_FAILED = 3,
  /**
   * Writing the temporary PCM staging file failed (disk full, sandbox
   * path unwritable, ...).
   */
  OPEN_ASR_STATUS_IO_ERROR = 4,
  /**
   * A panic was caught at the FFI boundary and converted to an error
   * instead of unwinding into the caller. This should not happen in
   * normal operation; it indicates an engine bug.
   */
  OPEN_ASR_STATUS_INTERNAL_PANIC = 5,
} OpenAsrStatus;

/**
 * PCM sample encoding accepted by [`openasr_transcribe_pcm`].
 */
typedef enum OpenAsrPcmFormat {
  /**
   * 32-bit float samples in `[-1.0, 1.0]`.
   */
  OPEN_ASR_PCM_FORMAT_F32 = 0,
  /**
   * 16-bit signed integer samples (standard PCM WAV encoding).
   */
  OPEN_ASR_PCM_FORMAT_S16 = 1,
} OpenAsrPcmFormat;

/**
 * Opaque handle to a validated local `.oasr` model pack path. Obtained from
 * [`openasr_model_open`], released with [`openasr_model_close`].
 *
 * This does not keep decoded weights resident: the underlying engine loads
 * the pack fresh for each [`openasr_transcribe_pcm`] call (matching the CLI's
 * own per-request load path), so the handle's job is to validate the pack
 * once up front and fail closed before any transcription is attempted with a
 * bad path.
 */
typedef struct OpenAsrModel OpenAsrModel;

/**
 * Opaque transcription result. Free with [`openasr_result_free`]; read it
 * through `openasr_result_*` accessor functions.
 */
typedef struct OpenAsrResult OpenAsrResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the engine version (the workspace product version), as a static,
 * NUL-terminated UTF-8 string. Never null, never freed by the caller.
 */
const char *openasr_version(void);

/**
 * Loads (validates) a local `.oasr` model pack and returns an opaque handle
 * through `out_model`. Fails closed -- with [`OpenAsrStatus::ModelLoadFailed`]
 * and no handle written -- if the path is missing, not UTF-8, a directory, or
 * not a recognized OpenASR runtime pack.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string. `out_model` must be
 * a valid, non-null pointer to a `*mut OpenAsrModel` the caller owns.
 */
enum OpenAsrStatus openasr_model_open(const char *path, struct OpenAsrModel **out_model);

/**
 * Frees a handle returned by [`openasr_model_open`]. Null is accepted and is
 * a no-op (matches `free`/whisper.cpp convention).
 *
 * # Safety
 * `model`, if non-null, must be a handle previously returned by
 * [`openasr_model_open`] and not already freed.
 */
void openasr_model_close(struct OpenAsrModel *model);

/**
 * Transcribes one whole in-memory 16 kHz mono PCM buffer and writes a result
 * through `out_result`. `pcm_len_samples` counts samples (not bytes/frames).
 * Only mono 16 kHz input is accepted in v1 -- resampling/downmixing is the
 * caller's responsibility; anything else fails closed with
 * [`OpenAsrStatus::InvalidArgument`] rather than silently reinterpreting the
 * buffer. Read the result with the `openasr_result_*` accessors, then free it
 * with [`openasr_result_free`].
 *
 * # Safety
 * `model` must be a live handle from [`openasr_model_open`]. `pcm` must
 * point to at least `pcm_len_samples` samples of the given `format` (4 bytes
 * each for F32, 2 bytes each for S16). `out_result` must be a valid,
 * non-null pointer to a `*mut OpenAsrResult` the caller owns.
 */
enum OpenAsrStatus openasr_transcribe_pcm(struct OpenAsrModel *model,
                                          const void *pcm,
                                          uintptr_t pcm_len_samples,
                                          enum OpenAsrPcmFormat format,
                                          uint32_t sample_rate_hz,
                                          bool with_segments,
                                          struct OpenAsrResult **out_result);

/**
 * Frees a result returned by [`openasr_transcribe_pcm`]. Null is accepted
 * and is a no-op.
 *
 * # Safety
 * `result`, if non-null, must have been previously returned by
 * [`openasr_transcribe_pcm`] and not already freed.
 */
void openasr_result_free(struct OpenAsrResult *result);

/**
 * Returns the full transcript text, UTF-8 and NUL-terminated. Valid until
 * `result` is freed. Null only if `result` itself is null.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_text(const struct OpenAsrResult *result);

/**
 * Returns the detected/requested language tag (e.g. "en"), UTF-8 and
 * NUL-terminated, or null if `result` is null or the model family does not
 * report a language. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_language(const struct OpenAsrResult *result);

/**
 * Returns the number of segments in `result` (`0` if `result` is null or the
 * producing call passed `with_segments = false`).
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
uintptr_t openasr_result_segment_count(const struct OpenAsrResult *result);

/**
 * Returns segment `index`'s start time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_start(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s end time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_end(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s UTF-8, NUL-terminated text, or null if `result`
 * is null or `index` is out of range. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_segment_text(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns the last error message set on the calling thread by a failing
 * `openasr_*` call, or null if none is set / the last call succeeded. Valid
 * until the next `openasr_*` call on the same thread; copy it out if you
 * need it longer. Never freed by the caller.
 */
const char *openasr_last_error_message(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENASR_H */
