/* Generated by cbindgen from crates/openasr-ffi/src/lib.rs. Do not edit by
 * hand -- run scripts/generate-ffi-header.sh to regenerate. */

#ifndef OPENASR_H
#define OPENASR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned by every `openasr_*` call that can fail. `Ok` is
 * always `0`; every other variant means the requested handle/buffer was not
 * produced (or not mutated) and the caller should consult
 * [`openasr_last_error_message`].
 */
typedef enum OpenAsrStatus {
  /**
   * Call succeeded.
   */
  OPEN_ASR_STATUS_OK = 0,
  /**
   * A required pointer was null, or an argument was out of the range this
   * v1 API supports (e.g. a sample rate other than 16000, or a channel
   * count other than mono).
   */
  OPEN_ASR_STATUS_INVALID_ARGUMENT = 1,
  /**
   * The `.oasr` path was rejected: missing, not a recognized runtime
   * format, or failed the local-path/format trust checks.
   */
  OPEN_ASR_STATUS_MODEL_LOAD_FAILED = 2,
  /**
   * The engine returned an error while transcribing (bad/corrupt pack
   * contents, unsupported model family, decode failure, ...).
   */
  OPEN_ASR_STATUS_TRANSCRIBE_FAILED = 3,
  /**
   * Writing the temporary PCM staging file failed (disk full, sandbox
   * path unwritable, ...).
   */
  OPEN_ASR_STATUS_IO_ERROR = 4,
  /**
   * A panic was caught at the FFI boundary and converted to an error
   * instead of unwinding into the caller. This should not happen in
   * normal operation; it indicates an engine bug.
   */
  OPEN_ASR_STATUS_INTERNAL_PANIC = 5,
} OpenAsrStatus;

/**
 * PCM sample encoding accepted by [`openasr_transcribe_pcm`].
 */
typedef enum OpenAsrPcmFormat {
  /**
   * 32-bit float samples in `[-1.0, 1.0]`.
   */
  OPEN_ASR_PCM_FORMAT_F32 = 0,
  /**
   * 16-bit signed integer samples (standard PCM WAV encoding).
   */
  OPEN_ASR_PCM_FORMAT_S16 = 1,
} OpenAsrPcmFormat;

/**
 * Hardware target for a streaming session's decode, mirroring
 * [`openasr_core::NativeAsrHardwareTarget`]. `Auto` lets the runtime choose;
 * on iOS/macOS only `Auto`, `Cpu`, `Accelerated`, and `AppleSilicon` are
 * meaningful (the SDK is CPU-only today -- see `docs/SDK_IOS_MACOS.md`), but
 * the full set is mapped so the contract does not silently drop a value.
 */
typedef enum OpenAsrHardwareTarget {
  OPEN_ASR_HARDWARE_TARGET_AUTO = 0,
  OPEN_ASR_HARDWARE_TARGET_CPU = 1,
  OPEN_ASR_HARDWARE_TARGET_ACCELERATED = 2,
  OPEN_ASR_HARDWARE_TARGET_APPLE_SILICON = 3,
  OPEN_ASR_HARDWARE_TARGET_NVIDIA_CUDA = 4,
  OPEN_ASR_HARDWARE_TARGET_AMD_GPU = 5,
  OPEN_ASR_HARDWARE_TARGET_INTEL_CPU = 6,
  OPEN_ASR_HARDWARE_TARGET_INTEL_GPU = 7,
} OpenAsrHardwareTarget;

/**
 * The kind of an incremental streaming transcript event, mirroring
 * [`openasr_core::StreamingEventKind`].
 */
typedef enum OpenAsrStreamingEventKind {
  /**
   * A mutable in-progress hypothesis for the active utterance, superseded by
   * later events carrying the same segment id.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_PARTIAL = 0,
  /**
   * A settled segment, emitted at a VAD speech pause or at `finish`.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_COMMITTED = 1,
  /**
   * A post-final correction to an already-committed segment.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_REVISION = 2,
} OpenAsrStreamingEventKind;

/**
 * Opaque handle to a validated local `.oasr` model pack path. Obtained from
 * [`openasr_model_open`], released with [`openasr_model_close`].
 *
 * This does not keep decoded weights resident: the underlying engine loads
 * the pack fresh for each [`openasr_transcribe_pcm`] call (matching the CLI's
 * own per-request load path), so the handle's job is to validate the pack
 * once up front and fail closed before any transcription is attempted with a
 * bad path.
 */
typedef struct OpenAsrModel OpenAsrModel;

/**
 * Opaque transcription result. Free with [`openasr_result_free`]; read it
 * through `openasr_result_*` accessor functions.
 */
typedef struct OpenAsrResult OpenAsrResult;

/**
 * Opaque batch of streaming events produced by one [`openasr_streaming_feed`]
 * call. Read it through the `openasr_streaming_event_*` accessors, then free
 * it with [`openasr_streaming_events_free`]. Mirrors [`OpenAsrResult`]: the
 * events own Rust-side strings that are not a valid C value type, so they are
 * read by index rather than returned as a raw struct array.
 */
typedef struct OpenAsrStreamingEvents OpenAsrStreamingEvents;

/**
 * Opaque handle to an in-process streaming transcription session over a local
 * `.oasr` pack. Created with [`openasr_streaming_session_open`], driven with
 * [`openasr_streaming_feed`], and consumed by [`openasr_streaming_finish`]
 * (which returns the final transcript and frees the session) or discarded with
 * [`openasr_streaming_free`].
 */
typedef struct OpenAsrStreamingSession OpenAsrStreamingSession;

/**
 * Configuration for [`openasr_streaming_session_open`]. Pass a null pointer to
 * use the engine defaults (partial results on, word timestamps off, VAD on,
 * auto hardware, default poll cadence). All fields are plain C values so the
 * struct is a valid `#[repr(C)]` type; `language` is an optional borrowed C
 * string (null = auto-detect), read only during the open call.
 */
typedef struct OpenAsrStreamingConfig {
  /**
   * Emit mutable `Partial` events as audio arrives.
   */
  bool partial_results;
  /**
   * Attach per-word timings to events when the family supports them.
   */
  bool word_timestamps;
  /**
   * Run an energy VAD that commits a segment at each speech pause. When
   * false, the whole stream is one utterance finalized only at `finish`.
   */
  bool enable_vad;
  /**
   * Optional decode language hint (e.g. "en"), or null to auto-detect. Only
   * borrowed for the duration of the open call.
   */
  const char *language;
  /**
   * Hardware target for the decode session.
   */
  enum OpenAsrHardwareTarget hardware_target;
  /**
   * Inference thread cap; `0` uses the per-family default.
   */
  uint16_t inference_threads;
  /**
   * New audio (ms) to accumulate before polling the engine for a partial
   * re-decode; `0` uses the engine default. Values below the 20 ms frame
   * size are clamped up by the engine.
   */
  uint64_t partial_poll_interval_ms;
} OpenAsrStreamingConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the engine version (the workspace product version), as a static,
 * NUL-terminated UTF-8 string. Never null, never freed by the caller.
 */
const char *openasr_version(void);

/**
 * Loads (validates) a local `.oasr` model pack and returns an opaque handle
 * through `out_model`. Fails closed -- with [`OpenAsrStatus::ModelLoadFailed`]
 * and no handle written -- if the path is missing, not UTF-8, a directory, or
 * not a recognized OpenASR runtime pack.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string. `out_model` must be
 * a valid, non-null pointer to a `*mut OpenAsrModel` the caller owns.
 */
enum OpenAsrStatus openasr_model_open(const char *path, struct OpenAsrModel **out_model);

/**
 * Frees a handle returned by [`openasr_model_open`]. Null is accepted and is
 * a no-op (matches `free`/whisper.cpp convention).
 *
 * # Safety
 * `model`, if non-null, must be a handle previously returned by
 * [`openasr_model_open`] and not already freed.
 */
void openasr_model_close(struct OpenAsrModel *model);

/**
 * Transcribes one whole in-memory 16 kHz mono PCM buffer and writes a result
 * through `out_result`. `pcm_len_samples` counts samples (not bytes/frames).
 * Only mono 16 kHz input is accepted in v1 -- resampling/downmixing is the
 * caller's responsibility; anything else fails closed with
 * [`OpenAsrStatus::InvalidArgument`] rather than silently reinterpreting the
 * buffer. Read the result with the `openasr_result_*` accessors, then free it
 * with [`openasr_result_free`].
 *
 * # Safety
 * `model` must be a live handle from [`openasr_model_open`]. `pcm` must
 * point to at least `pcm_len_samples` samples of the given `format` (4 bytes
 * each for F32, 2 bytes each for S16). `out_result` must be a valid,
 * non-null pointer to a `*mut OpenAsrResult` the caller owns.
 */
enum OpenAsrStatus openasr_transcribe_pcm(struct OpenAsrModel *model,
                                          const void *pcm,
                                          uintptr_t pcm_len_samples,
                                          enum OpenAsrPcmFormat format,
                                          uint32_t sample_rate_hz,
                                          bool with_segments,
                                          struct OpenAsrResult **out_result);

/**
 * Frees a result returned by [`openasr_transcribe_pcm`]. Null is accepted
 * and is a no-op.
 *
 * # Safety
 * `result`, if non-null, must have been previously returned by
 * [`openasr_transcribe_pcm`] and not already freed.
 */
void openasr_result_free(struct OpenAsrResult *result);

/**
 * Returns the full transcript text, UTF-8 and NUL-terminated. Valid until
 * `result` is freed. Null only if `result` itself is null.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_text(const struct OpenAsrResult *result);

/**
 * Returns the detected/requested language tag (e.g. "en"), UTF-8 and
 * NUL-terminated, or null if `result` is null or the model family does not
 * report a language. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_language(const struct OpenAsrResult *result);

/**
 * Returns the number of segments in `result` (`0` if `result` is null or the
 * producing call passed `with_segments = false`).
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
uintptr_t openasr_result_segment_count(const struct OpenAsrResult *result);

/**
 * Returns segment `index`'s start time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_start(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s end time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_end(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s UTF-8, NUL-terminated text, or null if `result`
 * is null or `index` is out of range. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_segment_text(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Opens an in-process streaming transcription session over the local `.oasr`
 * pack at `path` and writes an opaque handle through `out_session`. Fails
 * closed -- with [`OpenAsrStatus::ModelLoadFailed`] and no handle written --
 * if the path is missing, not UTF-8, or not a pack a native model family
 * recognizes / can stream. Never touches the network.
 *
 * Pass a null `config` to use the engine defaults; otherwise `config` is read
 * (and its `language`, if non-null, borrowed) only for the duration of this
 * call.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string. `config`, if
 * non-null, must point to a valid [`OpenAsrStreamingConfig`] whose `language`
 * is null or a valid NUL-terminated UTF-8 C string. `out_session` must be a
 * valid, non-null pointer to a `*mut OpenAsrStreamingSession` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_session_open(const char *path,
                                                  const struct OpenAsrStreamingConfig *config,
                                                  struct OpenAsrStreamingSession **out_session);

/**
 * Feeds a chunk of 16 kHz mono `f32` PCM (any length, including zero) into an
 * open streaming session and writes the incremental events it produced through
 * `out_events`: `Partial`s for the active utterance and a `Committed` event
 * whenever a VAD speech pause closes one. An empty chunk is accepted and yields
 * an empty (non-null) event batch. Read the batch with the
 * `openasr_streaming_event_*` accessors, then free it with
 * [`openasr_streaming_events_free`].
 *
 * # Safety
 * `session` must be a live handle from [`openasr_streaming_session_open`] (not
 * yet finished/freed). `pcm` must point to at least `pcm_len_samples` `f32`
 * samples (may be null only when `pcm_len_samples` is 0). `out_events` must be
 * a valid, non-null pointer to a `*mut OpenAsrStreamingEvents` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_feed(struct OpenAsrStreamingSession *session,
                                          const float *pcm,
                                          uintptr_t pcm_len_samples,
                                          struct OpenAsrStreamingEvents **out_events);

/**
 * Finishes a streaming session: drains any buffered tail audio, finalizes the
 * active utterance, and writes the assembled final [`OpenAsrResult`] (with
 * per-segment timestamps) through `out_result`. This **consumes** `session`:
 * whether it succeeds or fails, the handle is freed and must not be reused or
 * passed to [`openasr_streaming_free`]. Read the result with the
 * `openasr_result_*` accessors and free it with [`openasr_result_free`].
 *
 * # Safety
 * `session` must be a live handle from [`openasr_streaming_session_open`] that
 * has not already been finished or freed. `out_result` must be a valid,
 * non-null pointer to a `*mut OpenAsrResult` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_finish(struct OpenAsrStreamingSession *session,
                                            struct OpenAsrResult **out_result);

/**
 * Frees a streaming session without finishing it (aborts the stream). Null is
 * accepted and is a no-op. Do not call this on a handle already consumed by
 * [`openasr_streaming_finish`].
 *
 * # Safety
 * `session`, if non-null, must be a live handle from
 * [`openasr_streaming_session_open`] that has not been finished or freed.
 */
void openasr_streaming_free(struct OpenAsrStreamingSession *session);

/**
 * Returns the number of events in `events` (`0` if `events` is null).
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uintptr_t openasr_streaming_events_count(const struct OpenAsrStreamingEvents *events);

/**
 * Returns event `index`'s kind, or [`OpenAsrStreamingEventKind::Partial`] if
 * `events` is null or `index` is out of range (gate reads on
 * [`openasr_streaming_events_count`]).
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
enum OpenAsrStreamingEventKind openasr_streaming_event_kind(const struct OpenAsrStreamingEvents *events,
                                                            uintptr_t index);

/**
 * Returns event `index`'s text (UTF-8, NUL-terminated), or null if `events` is
 * null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_text(const struct OpenAsrStreamingEvents *events,
                                         uintptr_t index);

/**
 * Returns event `index`'s utterance id (UTF-8, NUL-terminated), or null if
 * `events` is null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_utterance_id(const struct OpenAsrStreamingEvents *events,
                                                 uintptr_t index);

/**
 * Returns event `index`'s segment id (UTF-8, NUL-terminated), or null if
 * `events` is null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_segment_id(const struct OpenAsrStreamingEvents *events,
                                               uintptr_t index);

/**
 * Returns event `index`'s detected language tag (e.g. "en"), UTF-8 and
 * NUL-terminated, or null if `events` is null, `index` is out of range, or the
 * family reported no language. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_language(const struct OpenAsrStreamingEvents *events,
                                             uintptr_t index);

/**
 * Returns event `index`'s monotonic revision number (higher supersedes lower
 * for the same segment id), or `0` if `events` is null or `index` is out of
 * range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_revision(const struct OpenAsrStreamingEvents *events,
                                          uintptr_t index);

/**
 * Returns event `index`'s start time in milliseconds, or `0` if `events` is
 * null or `index` is out of range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_start_ms(const struct OpenAsrStreamingEvents *events,
                                          uintptr_t index);

/**
 * Returns event `index`'s end time in milliseconds, or `0` if `events` is null
 * or `index` is out of range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_end_ms(const struct OpenAsrStreamingEvents *events,
                                        uintptr_t index);

/**
 * Frees an event batch returned by [`openasr_streaming_feed`]. Null is accepted
 * and is a no-op.
 *
 * # Safety
 * `events`, if non-null, must have been previously returned by
 * [`openasr_streaming_feed`] and not already freed.
 */
void openasr_streaming_events_free(struct OpenAsrStreamingEvents *events);

/**
 * Returns the last error message set on the calling thread by a failing
 * `openasr_*` call, or null if none is set / the last call succeeded. Valid
 * until the next `openasr_*` call on the same thread; copy it out if you
 * need it longer. Never freed by the caller.
 */
const char *openasr_last_error_message(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENASR_H */
