/* Generated by cbindgen from crates/openasr-ffi/src/lib.rs. Do not edit by
 * hand -- run scripts/generate-ffi-header.sh to regenerate. */

#ifndef OPENASR_H
#define OPENASR_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status codes returned by every `openasr_*` call that can fail. `Ok` is
 * always `0`; every other variant means the requested handle/buffer was not
 * produced (or not mutated) and the caller should consult
 * [`openasr_last_error_message`].
 */
typedef enum OpenAsrStatus {
  /**
   * Call succeeded.
   */
  OPEN_ASR_STATUS_OK = 0,
  /**
   * A required pointer was null, or an argument was out of the range this
   * v1 API supports (e.g. a sample rate other than 16000, or a channel
   * count other than mono).
   */
  OPEN_ASR_STATUS_INVALID_ARGUMENT = 1,
  /**
   * The `.oasr` path was rejected: missing, not a recognized runtime
   * format, or failed the local-path/format trust checks.
   */
  OPEN_ASR_STATUS_MODEL_LOAD_FAILED = 2,
  /**
   * The engine returned an error while transcribing (bad/corrupt pack
   * contents, unsupported model family, decode failure, ...).
   */
  OPEN_ASR_STATUS_TRANSCRIBE_FAILED = 3,
  /**
   * Writing the temporary PCM staging file failed (disk full, sandbox
   * path unwritable, ...).
   */
  OPEN_ASR_STATUS_IO_ERROR = 4,
  /**
   * A panic was caught at the FFI boundary and converted to an error
   * instead of unwinding into the caller. This should not happen in
   * normal operation; it indicates an engine bug.
   */
  OPEN_ASR_STATUS_INTERNAL_PANIC = 5,
  /**
   * The signed model catalog could not be fetched, verified, parsed, or
   * (for a pull) the requested model/quant could not be resolved from it.
   * The catalog is loaded through the same fail-closed signature pipeline
   * the CLI uses; a bad signature, epoch rollback, or unknown reference all
   * land here rather than producing an unverified result.
   */
  OPEN_ASR_STATUS_CATALOG_FAILED = 6,
  /**
   * A model-pack pull or local-pack install failed: a network/transport
   * error, a size/sha256 mismatch against the signed catalog, a failed
   * GGUF/runtime preflight, a restricted license not explicitly accepted,
   * an unsupported license class, or an install I/O error. Never a
   * partially-installed or unverified pack.
   */
  OPEN_ASR_STATUS_PULL_FAILED = 7,
  /**
   * A pull was stopped because the caller's cancel callback returned true.
   * Any partial download is cleaned up; nothing is installed.
   */
  OPEN_ASR_STATUS_PULL_CANCELED = 8,
  /**
   * The process-owned native execution services could not be constructed.
   */
  OPEN_ASR_STATUS_INITIALIZATION_FAILED = 9,
  /**
   * An opt-in remote (LAN) pairing, transcription, or realtime call failed:
   * TLS/TOFU pin mismatch, pairing rejection, transport error, or a remote
   * HTTP/WebSocket error. Consult [`openasr_last_error_message`].
   */
  OPEN_ASR_STATUS_REMOTE_FAILED = 10,
} OpenAsrStatus;

/**
 * PCM sample encoding accepted by [`openasr_transcribe_pcm`].
 */
typedef enum OpenAsrPcmFormat {
  /**
   * 32-bit float samples in `[-1.0, 1.0]`.
   */
  OPEN_ASR_PCM_FORMAT_F32 = 0,
  /**
   * 16-bit signed integer samples (standard PCM WAV encoding).
   */
  OPEN_ASR_PCM_FORMAT_S16 = 1,
} OpenAsrPcmFormat;

/**
 * Hardware target for a streaming session's decode, mirroring
 * [`openasr_core::NativeAsrHardwareTarget`]. `Auto` lets the runtime choose;
 * on iOS/macOS only `Auto`, `Cpu`, `Accelerated`, and `AppleSilicon` are
 * meaningful (the SDK is CPU-only today -- see `docs/SDK_IOS_MACOS.md`), but
 * the full set is mapped so the contract does not silently drop a value.
 */
typedef enum OpenAsrHardwareTarget {
  OPEN_ASR_HARDWARE_TARGET_AUTO = 0,
  OPEN_ASR_HARDWARE_TARGET_CPU = 1,
  OPEN_ASR_HARDWARE_TARGET_ACCELERATED = 2,
  OPEN_ASR_HARDWARE_TARGET_APPLE_SILICON = 3,
  OPEN_ASR_HARDWARE_TARGET_NVIDIA_CUDA = 4,
  OPEN_ASR_HARDWARE_TARGET_AMD_GPU = 5,
  OPEN_ASR_HARDWARE_TARGET_INTEL_CPU = 6,
  OPEN_ASR_HARDWARE_TARGET_INTEL_GPU = 7,
} OpenAsrHardwareTarget;

/**
 * The kind of an incremental streaming transcript event, mirroring
 * [`openasr_core::StreamingEventKind`].
 */
typedef enum OpenAsrStreamingEventKind {
  /**
   * A mutable in-progress hypothesis for the active utterance, superseded by
   * later events carrying the same segment id.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_PARTIAL = 0,
  /**
   * A settled segment, emitted at a VAD speech pause or at `finish`.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_COMMITTED = 1,
  /**
   * A post-final correction to an already-committed segment.
   */
  OPEN_ASR_STREAMING_EVENT_KIND_REVISION = 2,
} OpenAsrStreamingEventKind;

/**
 * The stage a [`openasr_pull_model`], [`openasr_install_local_pack`], or
 * [`openasr_install_local_pack_v2`] progress callback is reporting, mirroring
 * [`openasr_core::PullProgress`].
 */
typedef enum OpenAsrPullPhase {
  /**
   * The requested pack was already installed and verified on disk; no
   * download happened. `bytes_done` / `bytes_total` are 0.
   */
  OPEN_ASR_PULL_PHASE_USING_INSTALLED = 0,
  /**
   * The download is starting (or resuming). `bytes_done` is the resume
   * offset (0 for a fresh download); `bytes_total` is the full pack size.
   */
  OPEN_ASR_PULL_PHASE_STARTED = 1,
  /**
   * Download progress. `bytes_done` of `bytes_total` bytes fetched.
   */
  OPEN_ASR_PULL_PHASE_DOWNLOADING = 2,
  /**
   * The full pack is downloaded and its sha256 is being verified against the
   * catalog-pinned digest. `bytes_done` is bytes hashed; `bytes_total` is 0.
   */
  OPEN_ASR_PULL_PHASE_VERIFYING = 3,
  /**
   * The verified pack has been installed. `bytes_done` / `bytes_total` are 0.
   */
  OPEN_ASR_PULL_PHASE_INSTALLED = 4,
} OpenAsrPullPhase;

/**
 * Outcome of [`openasr_remote_poll_pairing`].
 */
typedef enum OpenAsrRemotePairingStatus {
  OPEN_ASR_REMOTE_PAIRING_STATUS_PENDING = 0,
  OPEN_ASR_REMOTE_PAIRING_STATUS_APPROVED = 1,
} OpenAsrRemotePairingStatus;

/**
 * Opaque handle to a fetched-and-verified model catalog. Obtained from
 * [`openasr_catalog_fetch`], read as JSON with [`openasr_catalog_json`], passed
 * to [`openasr_pull_model`], [`openasr_install_local_pack`], or
 * [`openasr_install_local_pack_v2`] as the verified source of every
 * model/quant/url/sha the pull may resolve, and released with
 * [`openasr_catalog_free`].
 *
 * The catalog JSON is serialized once, at fetch time, from the verified +
 * forward-compatibility-filtered [`ModelCatalog`], so [`openasr_catalog_json`]
 * can hand back a borrowed pointer with no per-call allocation.
 */
typedef struct OpenAsrCatalog OpenAsrCatalog;

/**
 * Opaque handle to a fully verified local `.oasr` model pack. Obtained from
 * [`openasr_model_open`], released with [`openasr_model_close`].
 *
 * The handle retains the exact `VerifiedPack` generation through its native
 * adapter/model-pack binding. Decoded weights remain owned by the shared
 * execution services and may be evicted independently, but transcription
 * never downgrades this handle back to a bare path and re-verifies a possibly
 * replaced file.
 */
typedef struct OpenAsrEngine OpenAsrEngine;

typedef struct OpenAsrModel OpenAsrModel;

/**
 * Opaque remote-compute client. Create with [`openasr_remote_client_create`]
 * or restore with [`openasr_remote_restore_connected`]; free with
 * [`openasr_remote_client_free`]. Holds the pairing session and, once
 * approved, the bearer token inside the injected secret store -- never as a
 * C string the caller is expected to keep.
 *
 * **Not thread-safe.** Do not call any `openasr_remote_*` function on the same
 * client (or its realtime session) from multiple threads. Do not call any
 * `openasr_remote_*` function from an [`OpenAsrRemoteRealtimeEventCallback`].
 */
typedef struct OpenAsrRemoteClient OpenAsrRemoteClient;

/**
 * Opaque remote realtime session. Create with [`openasr_remote_realtime_start`],
 * stop with [`openasr_remote_realtime_stop`].
 */
typedef struct OpenAsrRemoteRealtime OpenAsrRemoteRealtime;

/**
 * Opaque transcription result. Free with [`openasr_result_free`]; read it
 * through `openasr_result_*` accessor functions.
 */
typedef struct OpenAsrResult OpenAsrResult;

/**
 * Opaque batch of streaming events produced by one [`openasr_streaming_feed`]
 * call. Read it through the `openasr_streaming_event_*` accessors, then free
 * it with [`openasr_streaming_events_free`]. Mirrors [`OpenAsrResult`]: the
 * events own Rust-side strings that are not a valid C value type, so they are
 * read by index rather than returned as a raw struct array.
 */
typedef struct OpenAsrStreamingEvents OpenAsrStreamingEvents;

/**
 * Opaque handle to an in-process streaming transcription session over a local
 * `.oasr` pack. Created with [`openasr_streaming_session_open`], driven with
 * [`openasr_streaming_feed`], and consumed by [`openasr_streaming_finish`]
 * (which returns the final transcript and frees the session) or discarded with
 * [`openasr_streaming_free`].
 */
typedef struct OpenAsrStreamingSession OpenAsrStreamingSession;

/**
 * Configuration for [`openasr_streaming_session_open`]. Pass a null pointer to
 * use the engine defaults (partial results on, word timestamps off, VAD on,
 * auto hardware, default poll cadence). All fields are plain C values so the
 * struct is a valid `#[repr(C)]` type; `language` is an optional borrowed C
 * string (null = auto-detect), read only during the open call.
 */
typedef struct OpenAsrStreamingConfig {
  /**
   * Emit mutable `Partial` events as audio arrives.
   */
  bool partial_results;
  /**
   * Attach per-word timings to events when the family supports them.
   */
  bool word_timestamps;
  /**
   * Run an energy VAD that commits a segment at each speech pause. When
   * false, the whole stream is one utterance finalized only at `finish`.
   */
  bool enable_vad;
  /**
   * Optional decode language hint (e.g. "en"), or null to auto-detect. Only
   * borrowed for the duration of the open call.
   */
  const char *language;
  /**
   * Hardware target for the decode session.
   */
  enum OpenAsrHardwareTarget hardware_target;
  /**
   * Inference thread cap; `0` uses the per-family default.
   */
  uint16_t inference_threads;
  /**
   * New audio (ms) to accumulate before polling the engine for a partial
   * re-decode; `0` uses the engine default. Values below the 20 ms frame
   * size are clamped up by the engine.
   */
  uint64_t partial_poll_interval_ms;
} OpenAsrStreamingConfig;

/**
 * Progress callback for a pull/install. Invoked synchronously on the calling
 * thread (the thread that called [`openasr_pull_model`],
 * [`openasr_install_local_pack`], or [`openasr_install_local_pack_v2`]), so
 * `user_data` need not be thread-safe. Pass a null function pointer to receive
 * no progress. The callback must not unwind (a panic across it is undefined
 * behavior); do the app-side marshalling to another thread inside it, not
 * around it.
 */
typedef void (*OpenAsrPullProgressCallback)(void *user_data,
                                            enum OpenAsrPullPhase phase,
                                            uint64_t bytes_done,
                                            uint64_t bytes_total);

/**
 * Cancellation callback for a pull. Polled synchronously on the calling thread
 * while the download runs; return `true` to cancel (the partial download is
 * cleaned up and [`OpenAsrStatus::PullCanceled`] is returned). Pass a null
 * function pointer to never cancel. Must not unwind.
 */
typedef bool (*OpenAsrPullCancelCallback)(void *user_data);

/**
 * Optional injected secret store (keychain / callback). Pass null to
 * [`openasr_remote_client_create`] / [`openasr_remote_restore_connected`] to
 * use an in-memory store. A non-null vtable must provide `store`, `load`, and
 * `free_secret`; missing any of those fails closed instead of falling back to
 * an in-memory store. `delete_secret` is optional.
 *
 * `store`: `secret` is valid only for the duration of this callback. The
 * implementor must copy the bytes if they need to retain them.
 *
 * `load` must write a freshly allocated C string to `out_secret` on success
 * (0) or null if the account is missing. `free_secret` must free that string;
 * the FFI copies the secret into Rust and immediately calls `free_secret`. A
 * successful non-null `load` without `free_secret` is an error.
 */
typedef struct OpenAsrRemoteSecretStore {
  void *user_data;
  int32_t (*store)(void *user_data, const char *account, const char *secret);
  int32_t (*load)(void *user_data, const char *account, char **out_secret);
  void (*free_secret)(char *secret);
  int32_t (*delete_secret)(void *user_data, const char *account);
} OpenAsrRemoteSecretStore;

/**
 * Incremental realtime event callback. `text` is valid only for the duration
 * of the call. The callback may run on a background thread. **Do not call any
 * `openasr_remote_*` function from this callback** -- the client and session
 * are not re-entrant.
 */
typedef void (*OpenAsrRemoteRealtimeEventCallback)(void *user_data, const char *text);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the engine version (the workspace product version), as a static,
 * NUL-terminated UTF-8 string. Never null, never freed by the caller.
 */
const char *openasr_version(void);

/**
 * Creates the explicit process-owned execution root shared by batch,
 * streaming, model-market eviction, and idle unload. Free it with
 * [`openasr_engine_free`] after every dependent handle has been released.
 *
 * # Safety
 * `out_engine` must point to writable storage for one `*mut OpenAsrEngine`.
 */
enum OpenAsrStatus openasr_engine_create(struct OpenAsrEngine **out_engine);

/**
 * Frees an engine handle. Null is accepted and is a no-op. Dependent model,
 * catalog, and streaming handles retain their own `Arc`, so destruction order
 * is safe, though callers should normally release dependents first.
 *
 * # Safety
 * `engine`, if non-null, must be a live handle from [`openasr_engine_create`].
 */
void openasr_engine_free(struct OpenAsrEngine *engine);

/**
 * Releases idle native runtime caches owned by `engine` while preserving the
 * engine and its memory broker for later requests.
 *
 * # Safety
 * `engine` must be a live handle from [`openasr_engine_create`].
 */
enum OpenAsrStatus openasr_engine_unload_idle_runtime_caches(const struct OpenAsrEngine *engine);

/**
 * Loads (validates) a local `.oasr` model pack and returns an opaque handle
 * through `out_model`. Fails closed -- with [`OpenAsrStatus::ModelLoadFailed`]
 * and no handle written -- if the path is missing, not UTF-8, a directory, or
 * not a recognized OpenASR runtime pack.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string. `out_model` must be
 * a valid, non-null pointer to a `*mut OpenAsrModel` the caller owns.
 */
enum OpenAsrStatus openasr_model_open(const char *path, struct OpenAsrModel **out_model);

/**
 * Engine-aware form of [`openasr_model_open`]. Every model opened from the
 * same engine participates in the same execution policy and memory broker.
 *
 * # Safety
 * `engine` must be a live handle from [`openasr_engine_create`]; the remaining
 * arguments follow [`openasr_model_open`]'s contract.
 */
enum OpenAsrStatus openasr_model_open_with_engine(const struct OpenAsrEngine *engine,
                                                  const char *path,
                                                  struct OpenAsrModel **out_model);

/**
 * Frees a handle returned by [`openasr_model_open`]. Null is accepted and is
 * a no-op (matches `free`/whisper.cpp convention).
 *
 * # Safety
 * `model`, if non-null, must be a handle previously returned by
 * [`openasr_model_open`] and not already freed.
 */
void openasr_model_close(struct OpenAsrModel *model);

/**
 * Transcribes one whole in-memory 16 kHz mono PCM buffer and writes a result
 * through `out_result`. `pcm_len_samples` counts samples (not bytes/frames).
 * Only mono 16 kHz input is accepted in v1 -- resampling/downmixing is the
 * caller's responsibility; anything else fails closed with
 * [`OpenAsrStatus::InvalidArgument`] rather than silently reinterpreting the
 * buffer. Read the result with the `openasr_result_*` accessors, then free it
 * with [`openasr_result_free`].
 *
 * # Safety
 * `model` must be a live handle from [`openasr_model_open`]. `pcm` must
 * point to at least `pcm_len_samples` samples of the given `format` (4 bytes
 * each for F32, 2 bytes each for S16). `out_result` must be a valid,
 * non-null pointer to a `*mut OpenAsrResult` the caller owns.
 */
enum OpenAsrStatus openasr_transcribe_pcm(struct OpenAsrModel *model,
                                          const void *pcm,
                                          uintptr_t pcm_len_samples,
                                          enum OpenAsrPcmFormat format,
                                          uint32_t sample_rate_hz,
                                          bool with_segments,
                                          struct OpenAsrResult **out_result);

/**
 * Frees a result returned by [`openasr_transcribe_pcm`]. Null is accepted
 * and is a no-op.
 *
 * # Safety
 * `result`, if non-null, must have been previously returned by
 * [`openasr_transcribe_pcm`] and not already freed.
 */
void openasr_result_free(struct OpenAsrResult *result);

/**
 * Returns the full transcript text, UTF-8 and NUL-terminated. Valid until
 * `result` is freed. Null only if `result` itself is null.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_text(const struct OpenAsrResult *result);

/**
 * Returns the detected/requested language tag (e.g. "en"), UTF-8 and
 * NUL-terminated, or null if `result` is null or the model family does not
 * report a language. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_language(const struct OpenAsrResult *result);

/**
 * Returns the number of segments in `result` (`0` if `result` is null or the
 * producing call passed `with_segments = false`).
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
uintptr_t openasr_result_segment_count(const struct OpenAsrResult *result);

/**
 * Returns segment `index`'s start time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_start(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s end time in seconds, or `0.0` if `result` is
 * null or `index` is out of range.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
float openasr_result_segment_end(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Returns segment `index`'s UTF-8, NUL-terminated text, or null if `result`
 * is null or `index` is out of range. Valid until `result` is freed.
 *
 * # Safety
 * `result`, if non-null, must be a live handle from [`openasr_transcribe_pcm`].
 */
const char *openasr_result_segment_text(const struct OpenAsrResult *result, uintptr_t index);

/**
 * Opens an in-process streaming transcription session over the local `.oasr`
 * pack at `path` and writes an opaque handle through `out_session`. Fails
 * closed -- with [`OpenAsrStatus::ModelLoadFailed`] and no handle written --
 * if the path is missing, not UTF-8, or not a pack a native model family
 * recognizes / can stream. Never touches the network.
 *
 * Pass a null `config` to use the engine defaults; otherwise `config` is read
 * (and its `language`, if non-null, borrowed) only for the duration of this
 * call.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string. `config`, if
 * non-null, must point to a valid [`OpenAsrStreamingConfig`] whose `language`
 * is null or a valid NUL-terminated UTF-8 C string. `out_session` must be a
 * valid, non-null pointer to a `*mut OpenAsrStreamingSession` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_session_open(const char *path,
                                                  const struct OpenAsrStreamingConfig *config,
                                                  struct OpenAsrStreamingSession **out_session);

/**
 * Engine-aware form of [`openasr_streaming_session_open`]. Offline and
 * streaming handles opened from one engine share runtime caches and device
 * memory accounting.
 *
 * # Safety
 * `engine` must be a live handle from [`openasr_engine_create`]; the remaining
 * arguments follow [`openasr_streaming_session_open`]'s contract.
 */
enum OpenAsrStatus openasr_streaming_session_open_with_engine(const struct OpenAsrEngine *engine,
                                                              const char *path,
                                                              const struct OpenAsrStreamingConfig *config,
                                                              struct OpenAsrStreamingSession **out_session);

/**
 * Feeds a chunk of 16 kHz mono `f32` PCM (any length, including zero) into an
 * open streaming session and writes the incremental events it produced through
 * `out_events`: `Partial`s for the active utterance and a `Committed` event
 * whenever a VAD speech pause closes one. An empty chunk is accepted and yields
 * an empty (non-null) event batch. Read the batch with the
 * `openasr_streaming_event_*` accessors, then free it with
 * [`openasr_streaming_events_free`].
 *
 * # Safety
 * `session` must be a live handle from [`openasr_streaming_session_open`] (not
 * yet finished/freed). `pcm` must point to at least `pcm_len_samples` `f32`
 * samples (may be null only when `pcm_len_samples` is 0). `out_events` must be
 * a valid, non-null pointer to a `*mut OpenAsrStreamingEvents` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_feed(struct OpenAsrStreamingSession *session,
                                          const float *pcm,
                                          uintptr_t pcm_len_samples,
                                          struct OpenAsrStreamingEvents **out_events);

/**
 * Finishes a streaming session: drains any buffered tail audio, finalizes the
 * active utterance, and writes the assembled final [`OpenAsrResult`] (with
 * per-segment timestamps) through `out_result`. This **consumes** `session`:
 * whether it succeeds or fails, the handle is freed and must not be reused or
 * passed to [`openasr_streaming_free`]. Read the result with the
 * `openasr_result_*` accessors and free it with [`openasr_result_free`].
 *
 * # Safety
 * `session` must be a live handle from [`openasr_streaming_session_open`] that
 * has not already been finished or freed. `out_result` must be a valid,
 * non-null pointer to a `*mut OpenAsrResult` the caller owns.
 */
enum OpenAsrStatus openasr_streaming_finish(struct OpenAsrStreamingSession *session,
                                            struct OpenAsrResult **out_result);

/**
 * Frees a streaming session without finishing it (aborts the stream). Null is
 * accepted and is a no-op. Do not call this on a handle already consumed by
 * [`openasr_streaming_finish`].
 *
 * # Safety
 * `session`, if non-null, must be a live handle from
 * [`openasr_streaming_session_open`] that has not been finished or freed.
 */
void openasr_streaming_free(struct OpenAsrStreamingSession *session);

/**
 * Returns the number of events in `events` (`0` if `events` is null).
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uintptr_t openasr_streaming_events_count(const struct OpenAsrStreamingEvents *events);

/**
 * Returns event `index`'s kind, or [`OpenAsrStreamingEventKind::Partial`] if
 * `events` is null or `index` is out of range (gate reads on
 * [`openasr_streaming_events_count`]).
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
enum OpenAsrStreamingEventKind openasr_streaming_event_kind(const struct OpenAsrStreamingEvents *events,
                                                            uintptr_t index);

/**
 * Returns event `index`'s text (UTF-8, NUL-terminated), or null if `events` is
 * null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_text(const struct OpenAsrStreamingEvents *events,
                                         uintptr_t index);

/**
 * Returns event `index`'s utterance id (UTF-8, NUL-terminated), or null if
 * `events` is null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_utterance_id(const struct OpenAsrStreamingEvents *events,
                                                 uintptr_t index);

/**
 * Returns event `index`'s segment id (UTF-8, NUL-terminated), or null if
 * `events` is null or `index` is out of range. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_segment_id(const struct OpenAsrStreamingEvents *events,
                                               uintptr_t index);

/**
 * Returns event `index`'s detected language tag (e.g. "en"), UTF-8 and
 * NUL-terminated, or null if `events` is null, `index` is out of range, or the
 * family reported no language. Valid until `events` is freed.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
const char *openasr_streaming_event_language(const struct OpenAsrStreamingEvents *events,
                                             uintptr_t index);

/**
 * Returns event `index`'s monotonic revision number (higher supersedes lower
 * for the same segment id), or `0` if `events` is null or `index` is out of
 * range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_revision(const struct OpenAsrStreamingEvents *events,
                                          uintptr_t index);

/**
 * Returns event `index`'s start time in milliseconds, or `0` if `events` is
 * null or `index` is out of range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_start_ms(const struct OpenAsrStreamingEvents *events,
                                          uintptr_t index);

/**
 * Returns event `index`'s end time in milliseconds, or `0` if `events` is null
 * or `index` is out of range.
 *
 * # Safety
 * `events`, if non-null, must be a live handle from [`openasr_streaming_feed`].
 */
uint64_t openasr_streaming_event_end_ms(const struct OpenAsrStreamingEvents *events,
                                        uintptr_t index);

/**
 * Frees an event batch returned by [`openasr_streaming_feed`]. Null is accepted
 * and is a no-op.
 *
 * # Safety
 * `events`, if non-null, must have been previously returned by
 * [`openasr_streaming_feed`] and not already freed.
 */
void openasr_streaming_events_free(struct OpenAsrStreamingEvents *events);

/**
 * Returns the last error message set on the calling thread by a failing
 * `openasr_*` call, or null if none is set / the last call succeeded. Valid
 * until the next `openasr_*` call on the same thread; copy it out if you
 * need it longer. Never freed by the caller.
 */
const char *openasr_last_error_message(void);

/**
 * Fetches and verifies the signed model catalog, writing an opaque handle
 * through `out_catalog`. `catalog_url` is optional: null uses the built-in
 * production endpoint (the normal case); a non-null override is still held to
 * the same fail-closed signature/epoch pipeline. `home_dir` is the app's
 * OpenASR home (its sandbox directory), used for the verified catalog /
 * signature / epoch cache and as the offline fallback source.
 *
 * Fails closed with [`OpenAsrStatus::CatalogFailed`] and no handle if the
 * catalog cannot be fetched, its signature does not verify, the epoch rolled
 * back, or it does not parse. Network access happens only inside this explicit
 * call.
 *
 * # Safety
 * `catalog_url`, if non-null, must be a valid NUL-terminated UTF-8 C string.
 * `home_dir` must be a valid, non-empty, NUL-terminated UTF-8 C string.
 * `out_catalog` must be a valid, non-null pointer to a `*mut OpenAsrCatalog`
 * the caller owns.
 */
enum OpenAsrStatus openasr_catalog_fetch(const char *catalog_url,
                                         const char *home_dir,
                                         struct OpenAsrCatalog **out_catalog);

/**
 * Engine-aware form of [`openasr_catalog_fetch`]. Pull, install, and removal
 * operations using this catalog reclaim caches owned by the same engine that
 * serves batch and streaming requests.
 *
 * # Safety
 * `engine` must be a live handle from [`crate::openasr_engine_create`]; the
 * remaining arguments follow [`openasr_catalog_fetch`]'s contract.
 */
enum OpenAsrStatus openasr_catalog_fetch_with_engine(const struct OpenAsrEngine *engine,
                                                     const char *catalog_url,
                                                     const char *home_dir,
                                                     struct OpenAsrCatalog **out_catalog);

/**
 * Returns the verified catalog as a UTF-8, NUL-terminated JSON string (the
 * serialized [`ModelCatalog`]: models with their quants, sizes, sha256s,
 * languages, licenses, perf, etc.). Valid until `catalog` is freed; null only
 * if `catalog` is null. The app renders its market UI and its pull-consent
 * disclosure (model, quant, size, host, license) from this data.
 *
 * # Safety
 * `catalog`, if non-null, must be a live handle from [`openasr_catalog_fetch`].
 */
const char *openasr_catalog_json(const struct OpenAsrCatalog *catalog);

/**
 * Frees a catalog handle returned by [`openasr_catalog_fetch`]. Null is
 * accepted and is a no-op.
 *
 * # Safety
 * `catalog`, if non-null, must be a handle previously returned by
 * [`openasr_catalog_fetch`] and not already freed.
 */
void openasr_catalog_free(struct OpenAsrCatalog *catalog);

/**
 * Downloads, verifies, and installs the model pack identified by `reference`
 * (a catalog id or `id:quant`) after the app has obtained the user's consent.
 * This is the app-side equivalent of `openasr pull`: it resolves `reference`
 * against the verified `catalog`, streams the download from the catalog-pinned
 * url over https, checks the sha256 against the catalog digest, runs the
 * GGUF/runtime preflight, and installs atomically under `<home_dir>/models`.
 *
 * - `quant` is optional (null): with no quant pinned in `reference` or `quant`,
 *   the largest quant that fits this device's memory budget is chosen (an
 *   explicit `:quant` / `quant` always wins).
 * - `source` is optional (null): null uses the automatic download-source chain;
 *   otherwise one of `"hf"`, `"hf-mirror"`, `"weights"`, `"auto"`, `"china"`, or
 *   `"global"`. `"china"`/`"global"` pin the region-aware chain's direction
 *   explicitly (for callers, like the desktop app, that judge the region
 *   themselves) instead of `"auto"` judging it from locale/timezone.
 * - `accept_license` must be true to pull a non-commercial or gated-license
 *   model. Missing acceptance and unknown license classes fail closed with
 *   [`OpenAsrStatus::PullFailed`], so download consent cannot silently become
 *   license acceptance (mirrors the CLI's `--accept-license`).
 * - `progress_cb` / `cancel_cb` (both optional) are invoked synchronously on
 *   this thread; return `true` from `cancel_cb` to abort.
 * - `out_installed_json`, if non-null, receives a freshly-allocated
 *   UTF-8/NUL-terminated JSON object describing the installed pack (pull id,
 *   path, quant, size, sha256, ...). Free it with [`openasr_string_free`].
 *
 * Returns [`OpenAsrStatus::Ok`] on a verified install, [`OpenAsrStatus::PullCanceled`]
 * if `cancel_cb` aborted it, [`OpenAsrStatus::CatalogFailed`] if `reference`
 * could not be resolved, or [`OpenAsrStatus::PullFailed`] for a download /
 * verification / license / install failure. Never installs an unverified pack.
 *
 * # Safety
 * `catalog` must be a live handle from [`openasr_catalog_fetch`]. `reference`
 * and `home_dir` must be valid, non-empty, NUL-terminated UTF-8 C strings.
 * `quant` / `source`, if non-null, must be valid NUL-terminated UTF-8 C
 * strings. The callbacks, if non-null, must be valid function pointers that do
 * not unwind. `out_installed_json`, if non-null, must point to a writable
 * `*mut c_char` the caller owns.
 */
enum OpenAsrStatus openasr_pull_model(const struct OpenAsrCatalog *catalog,
                                      const char *reference,
                                      const char *quant,
                                      const char *source,
                                      bool accept_license,
                                      const char *home_dir,
                                      OpenAsrPullProgressCallback progress_cb,
                                      void *progress_user_data,
                                      OpenAsrPullCancelCallback cancel_cb,
                                      void *cancel_user_data,
                                      char **out_installed_json);

/**
 * Verifies and installs a `.oasr` pack the app already has on disk (e.g. one
 * side-loaded or copied into the app) without downloading it. The pack's
 * sha256/size must match an entry in the verified `catalog`, or the call fails
 * closed with [`OpenAsrStatus::PullFailed`] -- so a hand-supplied file cannot be
 * installed as a model the catalog never vouched for.
 *
 * `oasr_path` is the local pack path; `home_dir` is the app's OpenASR home.
 * `progress_cb` (optional) reports the verify/install phases. `out_installed_json`,
 * if non-null, receives a JSON object for the installed pack (free with
 * [`openasr_string_free`]).
 *
 * This ABI predates restricted local packs and therefore carries no explicit
 * license-acceptance bit. It remains source/binary compatible for permissive
 * packs, but fails closed for non-commercial, gated, or unknown license
 * classes. Use [`openasr_install_local_pack_v2`] for a restricted pack.
 *
 * # Safety
 * `catalog` must be a live handle from [`openasr_catalog_fetch`]. `oasr_path`
 * and `home_dir` must be valid, non-empty, NUL-terminated UTF-8 C strings.
 * `progress_cb`, if non-null, must be a valid non-unwinding function pointer.
 * `out_installed_json`, if non-null, must point to a writable `*mut c_char`.
 */
enum OpenAsrStatus openasr_install_local_pack(const struct OpenAsrCatalog *catalog,
                                              const char *oasr_path,
                                              const char *home_dir,
                                              OpenAsrPullProgressCallback progress_cb,
                                              void *progress_user_data,
                                              char **out_installed_json);

/**
 * License-aware version of [`openasr_install_local_pack`].
 *
 * `accept_license` must be true for non-commercial and vendor-gated packs.
 * Permissive packs do not require it, and unknown/future license classes are
 * always rejected. The decision comes from the same open-core policy used by
 * the CLI and HTTP server.
 *
 * # Safety
 * The pointer requirements are identical to [`openasr_install_local_pack`].
 */
enum OpenAsrStatus openasr_install_local_pack_v2(const struct OpenAsrCatalog *catalog,
                                                 const char *oasr_path,
                                                 bool accept_license,
                                                 const char *home_dir,
                                                 OpenAsrPullProgressCallback progress_cb,
                                                 void *progress_user_data,
                                                 char **out_installed_json);

/**
 * Lists the installed model packs under `home_dir`, writing a
 * freshly-allocated UTF-8/NUL-terminated JSON array (one object per installed
 * pack: pull id, path, model id, quant, size, sha256, ...) through `out_json`.
 * An empty install set yields `"[]"`, not null. Free the string with
 * [`openasr_string_free`]. Never touches the network.
 *
 * # Safety
 * `home_dir` must be a valid, non-empty, NUL-terminated UTF-8 C string.
 * `out_json` must be a valid, non-null pointer to a `*mut c_char` the caller
 * owns.
 */
enum OpenAsrStatus openasr_list_installed_json(const char *home_dir, char **out_json);

/**
 * Removes an installed model pack (by `reference`, a pull id or `id:quant`)
 * from under `home_dir`. `out_removed`, if non-null, is set to true when a pack
 * was found and removed, false when nothing matched. Removing a non-existent
 * pack is not an error (`out_removed = false`, status [`OpenAsrStatus::Ok`]).
 *
 * # Safety
 * `reference` and `home_dir` must be valid, non-empty, NUL-terminated UTF-8 C
 * strings. `out_removed`, if non-null, must point to a writable `bool` the
 * caller owns.
 */
enum OpenAsrStatus openasr_remove_model(const char *home_dir,
                                        const char *reference,
                                        bool *out_removed);

/**
 * Engine-aware form of [`openasr_remove_model`] that immediately reclaims
 * the removed pack's resident runtime caches from the supplied engine.
 *
 * # Safety
 * `engine` must be a live handle from [`crate::openasr_engine_create`]; the
 * remaining arguments follow [`openasr_remove_model`]'s contract.
 */
enum OpenAsrStatus openasr_remove_model_with_engine(const struct OpenAsrEngine *engine,
                                                    const char *home_dir,
                                                    const char *reference,
                                                    bool *out_removed);

/**
 * Frees a string returned through an `out_*_json` out-parameter by
 * [`openasr_pull_model`], [`openasr_install_local_pack`],
 * [`openasr_install_local_pack_v2`], or [`openasr_list_installed_json`]. Null
 * is accepted and is a no-op. Do not call this on [`openasr_catalog_json`]'s
 * return value (that is owned by the catalog handle) or on
 * [`openasr_last_error_message`]'s.
 *
 * # Safety
 * `string`, if non-null, must be a pointer previously produced by one of the
 * `out_*_json` out-parameters above and not already freed.
 */
void openasr_string_free(char *string);

/**
 * Creates a remote-compute client for a LAN host/port. `device_name` is sent
 * on [`openasr_remote_begin_pairing`]. `secret_store` may be null (in-memory).
 * A non-null store must provide `store`, `load`, and `free_secret`.
 *
 * **Not thread-safe.** See [`OpenAsrRemoteClient`].
 *
 * # Safety
 * `host` and `device_name` must be valid NUL-terminated UTF-8. `out_client`
 * must point to writable storage for one `*mut OpenAsrRemoteClient`.
 */
enum OpenAsrStatus openasr_remote_client_create(const char *host,
                                                uint16_t port,
                                                const char *device_name,
                                                const struct OpenAsrRemoteSecretStore *secret_store,
                                                struct OpenAsrRemoteClient **out_client);

/**
 * Restore a previously paired client from persisted host/port/fingerprint/
 * device id. The bearer token is loaded from `secret_store`; C must not pass
 * a token. Missing token or a fingerprint that does not match the stored
 * account fails closed.
 *
 * **Not thread-safe.** See [`OpenAsrRemoteClient`].
 *
 * # Safety
 * `host`, `device_name`, `fingerprint`, and `device_id` must be valid
 * NUL-terminated UTF-8. `out_client` must point to writable storage for one
 * `*mut OpenAsrRemoteClient`.
 */
enum OpenAsrStatus openasr_remote_restore_connected(const char *host,
                                                    uint16_t port,
                                                    const char *device_name,
                                                    const char *fingerprint,
                                                    const char *device_id,
                                                    const struct OpenAsrRemoteSecretStore *secret_store,
                                                    struct OpenAsrRemoteClient **out_client);

/**
 * Frees a remote client. Null is a no-op. Stop any realtime session first.
 *
 * # Safety
 * `client`, if non-null, must be a live handle from [`openasr_remote_client_create`].
 */
void openasr_remote_client_free(struct OpenAsrRemoteClient *client);

/**
 * Begin pairing. On success, `*out_safety_code` is a borrowed C string owned
 * by `client` (valid until the next mutating call or free). The TLS-vs-response
 * safety-code match has already been checked in `openasr-client`.
 *
 * # Safety
 * `client` must be live. `out_safety_code` must be writable.
 */
enum OpenAsrStatus openasr_remote_begin_pairing(struct OpenAsrRemoteClient *client,
                                                const char **out_safety_code);

/**
 * Poll an in-progress pairing request. Does not return the bearer token.
 *
 * # Safety
 * `client` must be live. `out_status` must be writable.
 */
enum OpenAsrStatus openasr_remote_poll_pairing(struct OpenAsrRemoteClient *client,
                                               enum OpenAsrRemotePairingStatus *out_status);

/**
 * Cancel in-progress pairing or disconnect a connected session. Drops the
 * stored token from the secret store when a device id is present.
 *
 * # Safety
 * `client` must be live.
 */
enum OpenAsrStatus openasr_remote_cancel(struct OpenAsrRemoteClient *client);

/**
 * Transcribe in-memory PCM through the paired remote server. 16 kHz mono.
 *
 * # Safety
 * Same pointer rules as [`crate::openasr_transcribe_pcm`].
 */
enum OpenAsrStatus openasr_remote_transcribe_pcm(struct OpenAsrRemoteClient *client,
                                                 const char *model,
                                                 const void *pcm,
                                                 uintptr_t pcm_len_samples,
                                                 enum OpenAsrPcmFormat format,
                                                 uint32_t sample_rate_hz,
                                                 struct OpenAsrResult **out_result);

/**
 * Start a pinned WSS realtime session. Completes the server handshake
 * (`audio.input.configure` then `session.start` for 16 kHz mono pcm16le) with
 * `model` before returning, so [`openasr_remote_realtime_feed`] is legal.
 * Incoming text frames are delivered to `on_message` (may be called from a
 * background thread, and must not call any `openasr_remote_*` function). The
 * bearer token stays on the Rust handle.
 *
 * **Not thread-safe.** See [`OpenAsrRemoteClient`].
 *
 * # Safety
 * `client` must be live and paired. `model` must be a valid NUL-terminated
 * UTF-8 C string. `out_session` must be writable.
 */
enum OpenAsrStatus openasr_remote_realtime_start(struct OpenAsrRemoteClient *client,
                                                 const char *model,
                                                 OpenAsrRemoteRealtimeEventCallback on_message,
                                                 void *user_data,
                                                 struct OpenAsrRemoteRealtime **out_session);

/**
 * Feed PCM16LE samples into an open remote realtime session. The session must
 * have been returned by a successful [`openasr_remote_realtime_start`]
 * (handshake completed). Feeding before start fails closed.
 *
 * # Safety
 * `session` must be live. `pcm16le` must point to `sample_count` i16 samples.
 */
enum OpenAsrStatus openasr_remote_realtime_feed(struct OpenAsrRemoteRealtime *session,
                                                const int16_t *pcm16le,
                                                uintptr_t sample_count);

/**
 * Stop a remote realtime session. Null is a no-op.
 *
 * # Safety
 * `session`, if non-null, must be a live handle from
 * [`openasr_remote_realtime_start`].
 */
void openasr_remote_realtime_stop(struct OpenAsrRemoteRealtime *session);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPENASR_H */
